#!/bin/sh
# Please, do not edit this file.
# Project configuration located in mk.conf

cc=cc
cflags=-pipe
ldflags=-lm
log=mklog
target=true

source ./mk.conf

die() { 
  [ "$1" = "" ] || $log die "$@"
  exit 1
}
try() {
  _trycmd="$@"
  eval "$@"
  [ $? -ne 0 ] && die "try: ${_trycmd}"
} 
mklog() {
  printf '\033[1;34m[%s]\033[0m %s\n' "$1" "$2"
}
make() {
  $log $@
  case "$1" in
    cc)
      $cc $cflags $fcflags -c -o $3 $2
      ;;
    ld)
      $cc -o $2 ${@:3} $ldflags $fldflags
      ;; 
  esac 
}

case "$target" in
  --argument)
    [ $# -lt 1 ] && die "usage: $0 \$target"
    target=$1
    ;;
  --env)
    [ "$TARGET" = "" ] && die "usage: TARGET=\$target $0"
    target="$TARGET"
    ;;
esac

$target || die "target failture: $target"

fcflags=""
fldflags=""
for feature in $features; do
    case $feature in
        xorg)
            fcflags="$fcflags -DXORG"
            fldflags="$fldflags -lX11"
            ;;
        *)
            die "Unknown feature: $feature"
            ;;
    esac
done

o=""
for s in $(ls s/*.c s/*/*.c); do 
  r="$(echo $s | sed 's/s/o/' | sed 's/\(\.c\)$/.o/')"
  mkdir -p $(dirname $r)
  try make cc $s $r
  o="$o $r"
done
#try make ld $appname "$(find -iname '*.o' | sed 's/$/ /g' | tr -d '\n')"
try make ld $appname "$o"
exit 0

